Change SetLadderData method from protected to public
Resolves error CS0122: 'FirstPersonPlayerMovement.SetLadderData(Vector3, Vector3)' is inaccessible due to its protection level